<?xml version="1.0"?>
<package format="3">
  <name>iga_iqp</name>
  <version>0.0.1</version>
  <description>GPS path publisher and RViz visualizer in C++ for ROS 2 Humble.</description>
  <maintainer email="i.marci158@gmail.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>

  <exec_depend>rviz2</exec_depend>
</package>